CSV creation for products
sofdev6-02-2024/LosAderezos pull request #17
Opened 2024-10-29 20:56 UTC by AngheloZambrana

2024-10-29 21:10 UTC, JCarlosHidalgoSosa approved these changes

2024-10-30 13:09 UTC, MayerliSantander requested changes

2024-10-30 13:09 UTC, MayerliSantander commented on infrastructure/environments/product-management/productDB/Data/Hipermaxi/Category.csv
> +0692aa3c-4080-463e-9da8-1cc5d76b5d78,Bebidas con alchol
Change alchol to alcohol

2024-10-30 13:15 UTC, AngheloZambrana commented on infrastructure/environments/product-management/productDB/Data/Hipermaxi/Category.csv
> +0692aa3c-4080-463e-9da8-1cc5d76b5d78,Bebidas con alchol
the name was changed

2024-10-30 18:05 UTC, MayerliSantander approved these changes

2024-10-30 18:07 UTC, merged