Feat/thirdauth
sofdev6-02-2024/LosAderezos pull request #34
Opened 2024-11-15 17:51 UTC by AngheloZambrana

2024-11-17 22:01 UTC, MayerliSantander requested changes

2024-11-17 22:01 UTC, MayerliSantander commented on apps/UserManagement/Backend/Controllers/TokenController.cs
> +        Console.WriteLine("fghsjkdfg");
Remove unnecessary console writeline

2024-11-17 22:01 UTC, MayerliSantander commented on apps/UserManagement/Backend/DTOs/WithID/SubsidiaryDTO.cs
> +}
Add endline

2024-11-17 22:01 UTC, MayerliSantander commented on apps/UserManagement/Backend/DTOs/WithID/SubsidiaryUsersDTO.cs
> +}
Add endline

2024-11-17 22:01 UTC, MayerliSantander commented on apps/UserManagement/Backend/DTOs/WithoutID/UserBySubsidiaryDTO.cs
>  }
Add endline

2024-11-17 22:01 UTC, MayerliSantander commented on apps/UserManagement/Backend/Services/ProductAPIService.cs
> +}
Add endline

2024-11-17 22:01 UTC, MayerliSantander commented on apps/UserManagement/Backend/Services/ServiceInterfaces/IProductAPIService.cs
> +}
Add endline

2024-11-17 22:35 UTC, DeidamiaFuentes approved these changes

2024-11-18 01:38 UTC, MayerliSantander approved these changes

2024-11-18 01:39 UTC, merged