Refactor: improve search bar
sofdev6-02-2024/LosAderezos pull request #51
Opened 2024-11-23 01:37 UTC by DeidamiaFuentes

In this PR I am improving the seachbar so that it filters the different items in the page, and it shows a list below oh the searchbar with related option depending on the actual text

2024-11-23 01:50 UTC, OropezaHugo requested changes
the search bar's options does not provide any advantage on searching more than remember the user the coincidences, those options when selected should act as a shortcut to the entire product name

2024-11-23 13:25 UTC, OropezaHugo approved these changes

2024-11-24 18:38 UTC, AngheloZambrana approved these changes

2024-11-24 19:28 UTC, MayerliSantander approved these changes

2024-11-24 19:28 UTC, merged