Services cors fixed
sofdev6-02-2024/LosAderezos pull request #54
Opened 2024-11-24 21:39 UTC by JCarlosHidalgoSosa

2024-11-24 21:45 UTC, OropezaHugo approved these changes

2024-11-25 13:39 UTC, DeidamiaFuentes requested changes

2024-11-25 13:39 UTC, DeidamiaFuentes commented on infrastructure/compose.yaml
> +        condition: service_started
You are missing the endline here

2024-11-25 14:04 UTC, JCarlosHidalgoSosa commented on infrastructure/compose.yaml
> +        condition: service_started
Already fixed.

2024-11-25 14:28 UTC, DeidamiaFuentes approved these changes

2024-11-25 14:29 UTC, merged