Feat/reports service
sofdev6-02-2024/LosAderezos pull request #60
Opened 2024-11-28 16:28 UTC by JCarlosHidalgoSosa

Added Product reports DAO's

2024-11-28 18:37 UTC, OropezaHugo approved these changes

2024-12-02 12:16 UTC, AngheloZambrana approved these changes

2024-12-02 15:29 UTC, DeidamiaFuentes requested changes
![image](https://github.com/user-attachments/assets/501b9570-9db0-476a-9b72-30dd92dab8d6)
It is missing the companyID that is needed t make certain reports in the future,  could you add it pls?

2024-12-04 17:48 UTC, JCarlosHidalgoSosa commented
> ![image](https://private-user-images.githubusercontent.com/134944300/391602835-501b9570-9db0-476a-9b72-30dd92dab8d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzQ3NjgsIm5iZiI6MTczMzMzNDQ2OCwicGF0aCI6Ii8xMzQ5NDQzMDAvMzkxNjAyODM1LTUwMWI5NTcwLTlkYjAtNDc2YS05YjcyLTMwZGQ5MmRhYjhkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNzQ3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTQ2MTU2ZGZjMWQzOWQwYWRmNGJhNDkyNGNmNTkzZTQ3YTFiMTM5MDVhMjBiNTBkZjI3M2Q4ZGViYWZlNTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.08uJ2jrPypLYdmOF7Uswo3B3r4am9dTNRMYsnIz49iM) It is missing the companyID that is needed t make certain reports in the future, could you add it pls?

Solved

2024-12-04 19:50 UTC, AngheloZambrana approved these changes

2024-12-04 20:21 UTC, DeidamiaFuentes approved these changes

2024-12-04 20:24 UTC, AngheloZambrana approved these changes

2024-12-04 20:31 UTC, merged